name: Main-Push

# Run this workflow every time a new commit pushed to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
      logLevel:
        description: 'The Logging Level'
        required: false
        default: 'low'

jobs:
  #allow editing of manual running parameters
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy Environment: ${{ github.event.inputs.deployEnvironment }}"
        echo "Log Level: ${{ github.event.inputs.logLevel }}"

  buildx-builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker label info
        id: docklabel
        run: |
          echo "::set-output name=sha::$GITHUB_SHA"
          echo "::set-output name=repo::$GITHUB_REPOSITORY"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Get Timestamp
        run: echo "timestamp=$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      -
        name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
#      -
#        name: Prep build image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          file: stages/Dockerfile.1
#          tags: |
#            ghcr.io/${{ steps.docklabel.outputs.repo }}:prep
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#      -
#        name: Build part image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          file: stages/Dockerfile.2
#          tags: |
#            ghcr.io/${{ steps.docklabel.outputs.repo }}:part
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: "CORES=${{ steps.cpu-cores.outputs.count }}"
          tags: |
            ghcr.io/${{ steps.docklabel.outputs.repo }}:${{ steps.docklabel.outputs.sha }}
            ghcr.io/${{ steps.docklabel.outputs.repo }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
